#!/bin/bash
#! This line is a comment
#! Make sure you only have comments and #SBATCH directives between here and the end of the #SBATCH directives, or things will break
#! Name of the job:
#SBATCH -J calculate_md_isf
#! Account name for group, use SL2 for paying queue:
#SBATCH -A ellis-sl3-cpu
#! Output filename:
#! %A means slurm job ID and %a means array index
#SBATCH --output="/home/jjhw3/logs/calculate_md_isf_%A_%a.out"
#! Errors filename:
#SBATCH --error="/home/jjhw3/logs/calculate_md_isf_%A_%a.err"

#! Number of nodes to be allocated  for the job (for single core jobs always leave this at 1)
#SBATCH --nodes=1
#! Number of tasks. By default SLURM assumes 1 task per node and 1 CPU per task. (for single core jobs always leave this at 1)
#SBATCH --ntasks=1
#! How many many cores will be allocated per task? (for single core jobs always leave this at 1)
#SBATCH --cpus-per-task=1
#! Estimated runtime: hh:mm:ss (job is force-stopped after if exceeded):
#SBATCH --time=10:00:00
#! Estimated maximum memory needed (job is force-stopped if exceeded):
#! RAM is allocated in ~5980mb blocks, you are charged per block used,
#! and unused fractions of blocks will not be usable by others.
#SBATCH --mem=5980mb
#! Submit a job array with index values between 0 and 31
#! NOTE: This must be a range, not a single number (i.e. specifying '32' here would only run one job, with index 32)
#SBATCH --array=101-200

#! This is the partition name.
#SBATCH -p skylake

#! mail alert at start, end and abortion of execution
#! emails will default to going to your email address
#! you can specify a different email address manually if needed.
#SBATCH --mail-type=ALL

#! Don't put any #SBATCH directives below this line

#! Modify the environment seen by the application. For this example we need the default modules.
. /etc/profile.d/modules.sh                # This line enables the module command
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment
module load python/3.8
source $HOME/venvs/md_venv/bin/activate
export PYTHONPATH="${PYTHONPATH}:${HOME}/code/gle_research/simulations/"

#! The variable $SLURM_ARRAY_TASK_ID contains the array index for each job.
#! In this example, each job will be passed its index, so each output file will contain a different value
echo "This is job" $SLURM_ARRAY_TASK_ID

#! Command line that we want to run:

#! export SLURM_ARRAY_TASK_ID=1

export BASE_DIR=$HOME/rds/hpc-work/md/calculate_md_isf
mkdir -p $BASE_DIR
mkdir -p $BASE_DIR/$SIZE
mkdir -p $BASE_DIR/$SIZE/$TEMPERATURE
export WORK_DIR=$BASE_DIR/$SIZE/$TEMPERATURE/$SLURM_ARRAY_TASK_ID
export CONFIG_FILE=$WORK_DIR/config.yml

rm -r $WORK_DIR
cp -R $HOME/code/gle_research/simulation_scripts/calculate_md_isf/calculate_md_isf_template $WORK_DIR

sed -i "s/TEMPERATURE/${TEMPERATURE}/g" "$CONFIG_FILE"
sed -i "s/SIZE/${SIZE}/g" "$CONFIG_FILE"
sed -i "s/MASS/${MASS}/g" "$CONFIG_FILE"
python $HOME/code/gle_research/simulation_scripts/calculate_md_isf/run_calculate_md_isf.py $WORK_DIR

python $HOME/code/gle_research/simulation_scripts/calculate_md_isf/calculate_alpha_dk.py $WORK_DIR