run_time: 100000
dt: 0.001
absorbate_mass: 23
temperature: temp_here
eta: 1.0
tau: 0.022
w_1: 0.0
basis_vectors:
  - [1.795, 1.795, 0]
  - [1.795, 0, 1.795]
  - [0, 1.795, 1.795]
conventional_cell:
  - [3.59, 0, 0]
  - [0, 3.59, 0]
  - [0, 0, 3.59]
free_plane_indices: [0, 0, 1]