run_time: 10000
dt: 0.001
absorbate_mass: 23
temperature: TEMPERATURE
eta: ETA
tau: 0.0
w_1: 0.0
basis_vectors:
  - [1.795, 1.795, 0]
  - [1.795, 0, 1.795]
  - [0, 1.795, 1.795]
conventional_cell:
  - [3.59, 0, 0]
  - [0, 3.59, 0]
  - [0, 0, 3.59]
free_plane_indices: [0, 0, 1]
