#!/bin/bash
#! This line is a comment
#! Make sure you only have comments and #SBATCH directives between here and the end of the #SBATCH directives, or things will break
#! Name of the job:
#SBATCH -J md_temp_range
#! Account name for group, use SL2 for paying queue:
#SBATCH -A ellis-sl3-cpu
#! Output filename:
#! %A means slurm job ID and %a means array index
#SBATCH --output="/home/jjhw3/logs/md_temp_range_%A_%a.out"
#! Errors filename:
#SBATCH --error="/home/jjhw3/logs/md_temp_range_%A_%a.err"

#! Number of nodes to be allocated  for the job (for single core jobs always leave this at 1)
#SBATCH --nodes=1
#! Number of tasks. By default SLURM assumes 1 task per node and 1 CPU per task. (for single core jobs always leave this at 1)
#SBATCH --ntasks=1
#! How many many cores will be allocated per task? (for single core jobs always leave this at 1)
#SBATCH --cpus-per-task=1
#! Estimated runtime: hh:mm:ss (job is force-stopped after if exceeded):
#SBATCH --time=2:00:00
#! Estimated maximum memory needed (job is force-stopped if exceeded):
#! RAM is allocated in ~5980mb blocks, you are charged per block used,
#! and unused fractions of blocks will not be usable by others.
#SBATCH --mem=5980mb
#! Submit a job array with index values between 0 and 31
#! NOTE: This must be a range, not a single number (i.e. specifying '32' here would only run one job, with index 32)
#SBATCH --array=4000-7000

#! This is the partition name.
#SBATCH -p skylake

#! mail alert at start, end and abortion of execution
#! emails will default to going to your email address
#! you can specify a different email address manually if needed.
#SBATCH --mail-type=ALL

#! Don't put any #SBATCH directives below this line

#! Modify the environment seen by the application. For this example we need the default modules.
. /etc/profile.d/modules.sh                # This line enables the module command
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment
module load python/3.8
source $HOME/venvs/md_temp_range/bin/activate
export PYTHONPATH="${PYTHONPATH}:${HOME}/code/gle_research/simulations/"

#! The variable $SLURM_ARRAY_TASK_ID contains the array index for each job.
#! In this example, each job will be passed its index, so each output file will contain a different value
echo "This is job" $SLURM_ARRAY_TASK_ID

#! Command line that we want to run:

#! export SLURM_ARRAY_TASK_ID=1

temperatures=(160 180 200 225 250 275 300)
temp=${temperatures[$(((SLURM_ARRAY_TASK_ID - 1) / 1000))]}
temp_index=$(((SLURM_ARRAY_TASK_ID - 1) % 1000))

mkdir -p $HOME/rds/hpc-work/gle/md_temp_range/
mkdir -p $HOME/rds/hpc-work/gle/md_temp_range/${temp}

rm -r $HOME/rds/hpc-work/gle/md_temp_range/${temp}/${temp_index}
cp -R $HOME/code/gle_research/simulation_scripts/md_temp_range/md_temp_range_template $HOME/rds/hpc-work/gle/md_temp_range/${temp}/${temp_index}
sed -i "s/temp_here/${temp}/g" "$HOME/rds/hpc-work/gle/md_temp_range/${temp}/${temp_index}/config.yml"

python $HOME/code/gle_research/simulation_scripts/md_temp_range/run_md_temp_range.py $HOME/rds/hpc-work/gle/md_temp_range/$temp/${temp_index}
python $HOME/code/gle_research/simulation_scripts/md_temp_range/calculate_isf.py $HOME/rds/hpc-work/gle/md_temp_range/$temp/${temp_index}

mkdir -p $HOME/rds/hpc-work/results/md_temp_range/
mkdir -p $HOME/rds/hpc-work/results/md_temp_range/$temp/
mkdir -p $HOME/rds/hpc-work/results/md_temp_range/$temp/${temp_index}

cp $HOME/rds/hpc-work/gle/md_temp_range/$temp/${temp_index}/alphas_dk.npy $HOME/rds/hpc-work/results/md_temp_range/$temp/${temp_index}
cp $HOME/rds/hpc-work/gle/md_temp_range/$temp/${temp_index}/dk_mags.npy $HOME/rds/hpc-work/results/md_temp_range/$temp/${temp_index}
cp $HOME/rds/hpc-work/gle/md_temp_range/$temp/${temp_index}/alpha_dk.png $HOME/rds/hpc-work/results/md_temp_range/$temp/${temp_index}
cp $HOME/rds/hpc-work/gle/md_temp_range/$temp/${temp_index}/temperature.png $HOME/rds/hpc-work/results/md_temp_range/$temp/${temp_index}
cp -r $HOME/rds/hpc-work/gle/md_temp_range/$temp/${temp_index}/ISFs $HOME/rds/hpc-work/results/md_temp_range/$temp/${temp_index}